#!/usr/bin/env python3
"""Shape + reorder the Arabic UI strings for TamaPoke's tiny display.

The firmware prints UTF-8 strictly left-to-right with a U8g2 bitmap font and
has no text shaping, so every string is prepared here:
  1. arabic_reshaper picks the contextual letter forms (U+FE70..FEFF, lam-alef).
  2. python-bidi lays the line out right-to-left (visual order).
  3. printf placeholders are protected as tokens during 1-2, then restored, and
     we assert they are still in snprintf argument order (left to right).
Output: C string initializers to paste into i18n.cpp (or run with --patch).

  pip install arabic-reshaper python-bidi
  python3 tools/gen_ar.py            # print the C block + checks
"""
import re, sys, os
import arabic_reshaper
from bidi.algorithm import get_display
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ar_strings import STRINGS, MED_NAME, MED_LBL, MED_DSC

PH = re.compile(r"\{(\d):(l?[usd])\}")
ARABIC = re.compile(r"[\u0600-\u06ff]")
LETTER = re.compile(r"[\u0621-\u064a]")  # base letters must all be shaped
TASHKEEL = re.compile(r"[\u064b-\u065f\u0670]")

def token(i, t):
    # numbers stay "European number" for the bidi algorithm, like the real digits
    # the firmware will print; %s args (names, already-ordered berry text) are an
    # opaque left-to-right run, like a Latin name.
    return ("9%d9%d9" % (i, i)) if t != "s" else ("QZ%s" % "ABCDEFGH"[i])

def convert(src):
    if not ARABIC.search(src):
        return src                         # pure Latin (e.g. "%s%s Lv.%u")
    assert not TASHKEEL.search(src), "no tashkeel please: " + src
    specs = {}
    def sub(m):
        i, t = int(m.group(1)), m.group(2)
        specs[i] = t
        return token(i, t[-1])
    s = PH.sub(sub, src)
    assert "%" not in s, "use {n:u} positional placeholders: " + src
    s = get_display(arabic_reshaper.reshape(s), base_dir="R")
    order = []
    s = re.sub(r"9(\d)9\d9|QZ([A-H])", lambda m: back_tok(m, specs, order), s)
    assert order == sorted(order) == list(range(1, len(order) + 1)), \
        "placeholders would reach snprintf out of order %r: %s" % (order, src)
    assert not LETTER.search(s), "unshaped letter left: " + src
    return s

def back_tok(m, specs, order):
    i = int(m.group(1)) if m.group(1) else "ABCDEFGH".index(m.group(2))
    order.append(i)
    return "%" + specs[i]

def c_lit(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def rows(items, per_line):
    return ["    " + ", ".join(c_lit(x) for x in items[i:i + per_line]) + ","
            for i in range(0, len(items), per_line)]

MARK = "// AR:%s (generated by tools/gen_ar.py - edit tools/ar_strings.py)"

def blocks():
    st = [convert(s) for s in STRINGS]
    b = {"STRINGS": ["  {"] + rows(st, 3) + ["  },"]}
    for name, arr in (("MED_NAME", MED_NAME), ("MED_LBL", MED_LBL), ("MED_DSC", MED_DSC)):
        b[name] = ["  { " + " ".join(c_lit(convert(x)) + "," for x in arr) + " },"]
    return b

def patch(path):
    src = open(path, encoding="utf-8").read().split("\n")
    out, i, n = [], 0, 0
    b = blocks()
    while i < len(src):
        line = src[i]
        out.append(line)
        for name, body in b.items():
            if line.strip() == MARK % name:
                i += 1
                while src[i].strip() != MARK % (name + "-END"):
                    i += 1
                out.extend(body)
                out.append(src[i])
                n += 1
        i += 1
    open(path, "w", encoding="utf-8").write("\n".join(out))
    print("patched %d tables in %s" % (n, path))

if __name__ == "__main__":
    if len(STRINGS) != 85 or not all(len(a) == 8 for a in (MED_NAME, MED_LBL, MED_DSC)):
        sys.exit("string count mismatch (STR_COUNT=85, MED_COUNT=8)")
    if len(sys.argv) > 1 and sys.argv[1] == "--patch":
        patch(sys.argv[2] if len(sys.argv) > 2 else
              os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "i18n.cpp"))
    else:
        for k, v in blocks().items():
            print(MARK % k); print("\n".join(v)); print(MARK % (k + "-END"))
